## Cálculo Tabla Provincias INE

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Definición de rutas de ficheros del Registro de la Propiedad 
export_rp_path = Path(r"C:\Users\LorenaMéndez\Desktop\Analisis_Precios_vivienda\Data - Registro Propiedad")
comparativa_compraventa_file = export_rp_path / "Export-ComparativaVivienda-RP.xlsx"

In [3]:
# Carga del fichero de comparativa de compraventa de vivienda
df_comparativa_compraventa_rp = pd.read_excel(comparativa_compraventa_file, sheet_name="Datos")

# Visualizar los resultados
df_comparativa_compraventa_rp

,ano,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,gar-num,gar-imp,gar-pm2,tras-num,tras-imp,tras-pm2
0,2007,1,Nacional,99,ESPAÑA,99,ESPAÑA,893310,174711,1961.66,345635,16844,1160.21,66561,6044,984.48
1,2007,1,Comunidad,1,Andalucía,98,ANDALUCÍA,176557,140505,1458.45,60792,16087,930.40,10691,6000,902.23
2,2007,1,Provincia,1,Andalucía,4,Almería,21968,126541,1471.91,7130,15716,946.15,1024,4547,777.96
3,2007,1,Provincia,1,Andalucía,11,Cádiz,27166,140283,1423.03,7176,15482,898.21,1111,5613,819.35
4,2007,1,Provincia,1,Andalucía,14,Córdoba,11872,116923,1187.94,5323,14322,753.53,499,5033,677.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5467,2025,4,Provincia,17,La Rioja,26,La Rioja,5497,131939,1399.76,2288,12506,915.80,400,5641,637.80
5468,2025,4,Comunidad,18,Ceuta,98,CEUTA,680,184418,2107.25,288,26498,1790.07,27,7839,1527.44
5469,2025,4,Provincia,18,Ceuta,51,Ceuta,680,184418,2107.25,288,26498,1790.07,27,7839,1527.44
5470,2025,4,Comunidad,19,Melilla,98,MELILLA,667,181172,1984.31,277,18947,1277.84,62,4530,1015.16
5471,2025,4,Provincia,19,Melilla,52,Melilla,667,181172,1984.31,277,18947,1277.84,62,4530,1015.16

In [4]:
#df_comparativa_compraventa_rp.columns

In [5]:
## 1. Calculo tabla Geografia
df_geo_prev = df_comparativa_compraventa_rp[['geo']]
# Eliminar duplicados
df_geografia = df_geo_prev.drop_duplicates()
# Renombrar columnas
df_geografia = df_geografia.rename(columns={"geo": "geografia"})
#Añadir la columna id_geo al dataframe
map_geo = {
    "Nacional": 1,
    "Comunidad": 2,
    "Provincia": 3
}
df_geografia["id_geo"] = df_geografia["geografia"].map(map_geo).fillna(99).astype(int)
# Ordenar columnas
df_geografia = df_geografia[['id_geo','geografia']]
# Visualizar los resultados
df_geografia

   id_geo  geografia
0       1   Nacional
1       2  Comunidad
2       3  Provincia

In [6]:
# Guardar resultado final de la tabla de geografia
df_geografia.to_excel("D_geografia_ine.xlsx", index=False)
df_geografia.to_csv("D_geografia_ine.csv", index=False)

In [7]:
## 2. Calculo tabla provincias INE
df_provincias_ine_prev = df_comparativa_compraventa_rp[['cod-ca','cod-prv', 'prv']]
# Eliminar duplicados
df_provincias_ine_prev = df_provincias_ine_prev.drop_duplicates()
# Filtrar el DF para sacar filas de comunidad y nacional
df_provincias_ine = df_provincias_ine_prev[(df_provincias_ine_prev["cod-prv"] != 99) & (df_provincias_ine_prev["cod-prv"] != 98)]
# Renombrar columnas
df_provincias_ine = df_provincias_ine.rename(columns={"prv": "nombre_provincia"})
# Añdir columnas id_provincia y nombre_provincia_completo
df_provincias_ine["id_provincia"] = (
    df_provincias_ine["cod-ca"].astype(str).str.zfill(2)
    + "-"
    + df_provincias_ine["cod-prv"].astype(str).str.zfill(2)
)
df_provincias_ine["nombre_provincia_completo"] = (
    df_provincias_ine["id_provincia"].astype(str).str.zfill(2)
    + " - "
    + df_provincias_ine["nombre_provincia"]
)

# Ordenar el Dataframe
df_provincias_ine = df_provincias_ine[['id_provincia','cod-ca', 'cod-prv', 'nombre_provincia', 'nombre_provincia_completo']]
# Visualizar los resultados
df_provincias_ine

,id_provincia,cod-ca,cod-prv,nombre_provincia,nombre_provincia_completo
2,01-04,1,4,Almería,01-04 - Almería
3,01-11,1,11,Cádiz,01-11 - Cádiz
4,01-14,1,14,Córdoba,01-14 - Córdoba
5,01-18,1,18,Granada,01-18 - Granada
6,01-21,1,21,Huelva,01-21 - Huelva
7,01-23,1,23,Jaén,01-23 - Jaén
8,01-29,1,29,Málaga,01-29 - Málaga
9,01-41,1,41,Sevilla,01-41 - Sevilla
11,02-22,2,22,Huesca,02-22 - Huesca
12,02-44,2,44,Teruel,02-44 - Teruel
13,02-50,2,50,Zaragoza,02-50 - Zaragoza
15,03-33,3,33,Asturias,03-33 - Asturias
17,04-07,4,7,Illes Balears,04-07 - Illes Balears
19,05-35,5,35,Las Palmas,05-35 - Las Palmas
20,05-38,5,38,Santa Cruz de Tenerife,05-38 - Santa Cruz de Tenerife
22,06-39,6,39,Cantabria,06-39 - Cantabria
24,07-05,7,5,Ávila,07-05 - Ávila
25,07-09,7,9,Burgos,07-09 - Burgos
26,07-24,7,24,León,07-24 - León
27,07-34,7,34,Palencia,07-34 - Palencia
28,07-37,7,37,Salamanca,07-37 - Salamanca
29,07-40,7,40,Segovia,07-40 - Segovia
30,07-42,7,42,Soria,07-42 - Soria
31,07-47,7,47,Valladolid,07-47 - Valladolid
32,07-49,7,49,Zamora,07-49 - Zamora
34,08-02,8,2,Albacete,08-02 - Albacete
35,08-13,8,13,Ciudad Real,08-13 - Ciudad Real
36,08-16,8,16,Cuenca,08-16 - Cuenca
37,08-19,8,19,Guadalajara,08-19 - Guadalajara
38,08-45,8,45,Toledo,08-45 - Toledo
40,09-08,9,8,Barcelona,09-08 - Barcelona
41,09-17,9,17,Girona,09-17 - Girona
42,09-25,9,25,Lleida,09-25 - Lleida
43,09-43,9,43,Tarragona,09-43 - Tarragona
45,10-03,10,3,Alicante / Alacant,10-03 - Alicante / Alacant
46,10-12,10,12,Castellón / Castelló,10-12 - Castellón / Castelló
47,10-46,10,46,Valencia / València,10-46 - Valencia / València
49,11-06,11,6,Badajoz,11-06 - Badajoz
50,11-10,11,10,Cáceres,11-10 - Cáceres
52,12-15,12,15,A Coruña,12-15 - A Coruña
53,12-27,12,27,Lugo,12-27 - Lugo
54,12-32,12,32,Ourense,12-32 - Ourense
55,12-36,12,36,Pontevedra,12-36 - Pontevedra
57,13-28,13,28,Madrid,13-28 - Madrid
59,14-30,14,30,Murcia,14-30 - Murcia
61,15-31,15,31,Navarra,15-31 - Navarra
63,16-01,16,1,Araba / Álava,16-01 - Araba / Álava
64,16-20,16,20,Gipuzkoa,16-20 - Gipuzkoa
65,16-48,16,48,Bizkaia,16-48 - Bizkaia
67,17-26,17,26,La Rioja,17-26 - La Rioja
69,18-51,18,51,Ceuta,18-51 - Ceuta
71,19-52,19,52,Melilla,19-52 - Melilla

In [8]:
#df_provincias_ine.columns

In [9]:
# Guardar resultado final de la tabla de provincias
df_provincias_ine.to_excel("D_provincias_ine.xlsx", index=False)
df_provincias_ine.to_csv("D_provincias_ine.csv", index=False)