## Tratamiento Datos Compraventa (RP)

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Definición de rutas de ficheros del Registro de la Propiedad 
export_rp_path = Path(r"C:\Users\LorenaMéndez\Desktop\Analisis_Precios_vivienda\Data - Registro Propiedad")
comparativa_compraventa_file = export_rp_path / "Export-ComparativaVivienda-RP.xlsx"

In [3]:
# Carga del fichero de comparativa de compraventa de vivienda
df_comparativa_compraventa_rp_prev = pd.read_excel(comparativa_compraventa_file, sheet_name="Datos")

# Incluir la clave compuesta de id_provincia
df_comparativa_compraventa_rp_prev["id_provincia"] = (
    df_comparativa_compraventa_rp_prev["cod-ca"].astype(str).str.zfill(2)
    + "-"
    + df_comparativa_compraventa_rp_prev["cod-prv"].astype(str).str.zfill(2)
)

# Añadir la columna id_geo al dataframe
map_geo = {
    "Nacional": 1,
    "Comunidad": 2,
    "Provincia": 3
}
df_comparativa_compraventa_rp_prev["id_geo"] = df_comparativa_compraventa_rp_prev["geo"].map(map_geo).fillna(99).astype(int)

# Renombrar columnas
df_comparativa_compraventa_rp_prev = df_comparativa_compraventa_rp_prev.rename(columns={"ano": "ejercicio"})

# Cálculo de la columna de fecha
# Mapeo trimestre -> mes
map_trim_mes = {
    1: "01",
    2: "04",
    3: "07",
    4: "10"
}
# Crear columna fecha
df_comparativa_compraventa_rp_prev["fecha"] = pd.to_datetime(
    df_comparativa_compraventa_rp_prev["ejercicio"].astype(str)
    + "-"
    + df_comparativa_compraventa_rp_prev["trim"].map(map_trim_mes)
    + "-01"
)

# Visualizar los resultados
df_comparativa_compraventa_rp_prev

,ejercicio,trim,geo,cod-ca,ca,cod-prv,prv,viv-num,viv-imp,viv-pm2,gar-num,gar-imp,gar-pm2,tras-num,tras-imp,tras-pm2,id_provincia,id_geo,fecha
0,2007,1,Nacional,99,ESPAÑA,99,ESPAÑA,893310,174711,1961.66,345635,16844,1160.21,66561,6044,984.48,99-99,1,2007-01-01
1,2007,1,Comunidad,1,Andalucía,98,ANDALUCÍA,176557,140505,1458.45,60792,16087,930.40,10691,6000,902.23,01-98,2,2007-01-01
2,2007,1,Provincia,1,Andalucía,4,Almería,21968,126541,1471.91,7130,15716,946.15,1024,4547,777.96,01-04,3,2007-01-01
3,2007,1,Provincia,1,Andalucía,11,Cádiz,27166,140283,1423.03,7176,15482,898.21,1111,5613,819.35,01-11,3,2007-01-01
4,2007,1,Provincia,1,Andalucía,14,Córdoba,11872,116923,1187.94,5323,14322,753.53,499,5033,677.64,01-14,3,2007-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5467,2025,4,Provincia,17,La Rioja,26,La Rioja,5497,131939,1399.76,2288,12506,915.80,400,5641,637.80,17-26,3,2025-10-01
5468,2025,4,Comunidad,18,Ceuta,98,CEUTA,680,184418,2107.25,288,26498,1790.07,27,7839,1527.44,18-98,2,2025-10-01
5469,2025,4,Provincia,18,Ceuta,51,Ceuta,680,184418,2107.25,288,26498,1790.07,27,7839,1527.44,18-51,3,2025-10-01
5470,2025,4,Comunidad,19,Melilla,98,MELILLA,667,181172,1984.31,277,18947,1277.84,62,4530,1015.16,19-98,2,2025-10-01
5471,2025,4,Provincia,19,Melilla,52,Melilla,667,181172,1984.31,277,18947,1277.84,62,4530,1015.16,19-52,3,2025-10-01

In [4]:
# Filtrado de columnas finales en el DF
df_comparativa_compraventa_rp = df_comparativa_compraventa_rp_prev[['fecha','ejercicio', 'trim','id_geo','cod-ca','id_provincia',
                                    'viv-num','viv-imp', 'viv-pm2', 'gar-num', 'gar-imp', 'gar-pm2', 'tras-num',
                                       'tras-imp', 'tras-pm2']]
# Visualizar los resultados
df_comparativa_compraventa_rp

,fecha,ejercicio,trim,id_geo,cod-ca,id_provincia,viv-num,viv-imp,viv-pm2,gar-num,gar-imp,gar-pm2,tras-num,tras-imp,tras-pm2
0,2007-01-01,2007,1,1,99,99-99,893310,174711,1961.66,345635,16844,1160.21,66561,6044,984.48
1,2007-01-01,2007,1,2,1,01-98,176557,140505,1458.45,60792,16087,930.40,10691,6000,902.23
2,2007-01-01,2007,1,3,1,01-04,21968,126541,1471.91,7130,15716,946.15,1024,4547,777.96
3,2007-01-01,2007,1,3,1,01-11,27166,140283,1423.03,7176,15482,898.21,1111,5613,819.35
4,2007-01-01,2007,1,3,1,01-14,11872,116923,1187.94,5323,14322,753.53,499,5033,677.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5467,2025-10-01,2025,4,3,17,17-26,5497,131939,1399.76,2288,12506,915.80,400,5641,637.80
5468,2025-10-01,2025,4,2,18,18-98,680,184418,2107.25,288,26498,1790.07,27,7839,1527.44
5469,2025-10-01,2025,4,3,18,18-51,680,184418,2107.25,288,26498,1790.07,27,7839,1527.44
5470,2025-10-01,2025,4,2,19,19-98,667,181172,1984.31,277,18947,1277.84,62,4530,1015.16
5471,2025-10-01,2025,4,3,19,19-52,667,181172,1984.31,277,18947,1277.84,62,4530,1015.16

In [5]:
#df_comparativa_compraventa_rp_prev.columns

In [6]:
# Guardar resultado final de la tabla de operaciones de compraventa
df_comparativa_compraventa_rp.to_excel("F_operaciones_compraventa_vivienda_rp.xlsx", index=False)
df_comparativa_compraventa_rp.to_csv("F_operaciones_compraventa_vivienda_rp.csv", index=False)